---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Genetic Evaluation in Livestock

## Notebooks
```{r, echo=FALSE}
s_misc_url <- 'https://charlotte-ngs.github.io/gelasmss2021/misc/'
tbl_nb_gel <- tibble::tibble(Week = c(10),
                             Date = c("2021-04-26"),
                             Topic = c(
                               paste0("[Model Selection](", s_misc_url, "20210426_model_selection.nb.html)", collapse = "")
                             ))
knitr::kable(tbl_nb_gel)
```


## Slides

```{r, echo=FALSE}
s_sl_url <- 'https://charlotte-ngs.github.io/gelasmss2021/sl/'
tbl_sl_gel <- tibble::tibble(Week    = c(8, 9, 10, 11, 12),
                         Date    = c("2021-04-12",
                                     "2021-04-19",
                                     "2021-04-26",
                                     "2021-05-03",
                                     "2021-05-10"),
                         Topic   = c(
                           "Introduction to Genetic Evaluation",
                           "Breeding Programs",
                           "Model Selection",
                           "Variance Components Estimation",
                           "Prediction of Breeding Values"
                         ),
                         Link    = c(
                           paste0("[original](", s_sl_url, "gel-w08-v01-intro.pdf)", 
                                  " | [with notes](", s_sl_url, "gel-w08-v01-intro_with_notes.pdf)", collapse = ''),
                           paste0("[original](", s_sl_url, "gel-w08-v02-bp.pdf)",
                                   " | [with notes](", s_sl_url, "gel-w08-v02-bp_with_notes.pdf)", collapse = ''),
                           paste0("[original](", s_sl_url, "gel-w09-v03-bp.pdf)",
                                  "| [with notes](", s_sl_url, "gel-w09-v03-bp_with_notes.pdf)", collapse = ""),
                           paste0("[original](", s_sl_url, "gel-w10-v04-vce.pdf)", 
                                  " | [with notes](", s_sl_url, "gel-w10-v04-vce_with_notes.pdf)", collapse = ""),
                           paste0("[original](", s_sl_url, "gel-w11-v05-pbv.pdf)",
                                  " | [with notes](", s_sl_url, "gel-w11-v05-pbv_with_notes.pdf)", collapse = "")
                         ))
knitr::kable(tbl_sl_gel)

```

## Videos

```{r, echo=FALSE}
tbl_video_gel <- tibble::tibble(Week = c(8, 9, 10, 11, 12),
                                Date = c("2021-04-12",
                                         "2021-04-19",
                                         "2021-04-26",
                                         "2021-05-03",
                                         "2021-05-10"),
                                Topic = c("[Introduction To Genetic Evaluation](https://youtu.be/7dBS2H1uydk)",
                                          "[Implementation of a Breeding Program](https://youtu.be/TqVPKJ97qko)",
                                          "[Model Selection](https://youtu.be/V2TUndbIJ4I)",
                                          "[Variance Components Estimation](https://youtu.be/9Tasa3qQcMs)",
                                          "[Prediction of Breeding Values](https://youtu.be/Wt90vXGq1cQ)"
                                          ))
knitr::kable(tbl_video_gel)
```


# Applied Statistical Methods
## Notebooks

```{r, echo=FALSE}
s_misc_url <- 'https://charlotte-ngs.github.io/gelasmss2021/misc/'
tbl_add_nb <- tibble::tibble(Week = c(4, 5, 6),
                     Date = c("2021-03-15",
                              "2021-03-22",
                              "2021-03-29"),
                     Topic = c(
                       paste0("[Fixed Linear Effect Models with Genomic Data](", 
                              s_misc_url,
                              "20210315_flem_problem_genomic_data.nb.html)", collapse = ''),
                       paste0("[Genomic Breeding Values Using MLEM](", 
                              s_misc_url, 
                              "20210322_mlem_genomic_data.nb.html)", collapse = ''),
                       paste0("[Bayesian Regression](", 
                              s_misc_url,
                              "20210329_bayes_regression.nb.html)", collapse = '')
                       ))
knitr::kable(tbl_add_nb)
```

## Slides

```{r, echo=FALSE}
s_sl_url <- 'https://charlotte-ngs.github.io/gelasmss2021/sl/'
tbl_sl <- tibble::tibble(Week    = c(1, 2, 3, 4, 5, 6),
                         Date    = c("2021-02-22",
                                     "2021-03-01",
                                     "2021-03-08",
                                     "2021-03-15",
                                     "2021-03-22",
                                     "2021-03-29"),
                         Topic   = c(
                           "Introduction to Applied Statistical Methods",
                           "Fixed Linear Effects Model",
                           "GBLUP",
                           "Genomic Relationship",
                           "LASSO",
                           "Bayes"
                         ),
                         Link    = c(
                           paste0("[original](", s_sl_url, "asm-w01-v01-intro.pdf) | ", 
                                  "[with notes](", s_sl_url, "asm-w01-v01-intro_with_notes.pdf)", collapse = ''),
                           paste0("[original](", s_sl_url, "asm-w02-v02-flem.pdf) | ", 
                                  "[with notes](", s_sl_url, "asm-w02-v02-flem_with_notes.pdf)", collapse = ''),
                           paste0("[original](", s_sl_url, "asm-w03-v03-gblup.pdf) | ",
                                  "[with notes](", s_sl_url, "asm-w03-v03-gblup_with_notes.pdf)", collapse = ''),
                           paste0("[original](", s_sl_url, "asm-w04-v04-grm.pdf) | ", 
                                  "[with notes](", s_sl_url, "asm-w04-v04-grm_with_notes.pdf)", collapse = ''), 
                           paste0("[original](", s_sl_url, "asm-w05-v05-lasso.pdf) | ", 
                                  "[with notes](", s_sl_url, "asm-w05-v05-lasso_with_notes.pdf)", collapse = ''),
                           paste0("[original](", s_sl_url, "asm-w06-v06-bayes.pdf) | ", 
                                  "[with notes](", s_sl_url, "asm-w06-v06-bayes_with_notes.pdf)", collapse = '')
                         ))
knitr::kable(tbl_sl)
```


## Video

```{r, echo=FALSE}
tbl_video <- tibble::tibble(Week = c(1, 2, 3, 4, 5, 6),
                            Date = c("2021-02-22",
                                     "2021-03-01",
                                     "2021-03-08", 
                                     "2021-03-15",
                                     "2021-03-22",
                                     "2021-03-29"),
                            Topic = c(
                              "[Introduction to Applied Statistical Methods](https://youtu.be/wMHUiDgAUI8)",
                              "[Fixed Linear Effects Models](https://youtu.be/uBhibtFV964)",
                              "[Regression Model and Exercises](https://youtu.be/OwvR1k4WMrE)",
                              "Preparation for GBLUP [Part 1](https://youtu.be/2IDhnLSEeqY) | [Part 2](https://youtu.be/6WzjfJ51xZU)",
                              "[Mixed Linear Effect Models and LASSO](https://youtu.be/wzRM5e3LYM8)",
                              "[Bayesian Approaches](https://youtu.be/vWtfBme6kZg)"
                            ))
knitr::kable(tbl_video)
```

