---
title: "Course Notes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Course Notes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains the list of links pointing to the different chapters in the course notes. 

## Applied Genetic Evaluation

```{r echo=FALSE}
s_cn_gel_url <- "https://charlotte-ngs.github.io/gelasmss2021/cn_gel/"
tbl_gel_chpt <- tibble::tibble(Week = c(8, 8, 9, 10, 11, 12),
                               Date = c("2021-04-12",
                                        "2021-04-12",
                                        "2021-04-19",
                                        "2021-04-26",
                                        "2021-05-03",
                                        "2021-05-10"),
                               Topic = c(
                                 paste0("[Introduction](", s_cn_gel_url, "01_intro.pdf)", collapse = ""),
                                 paste0("[Breeding Program](", s_cn_gel_url, "02_bp.pdf)", collapse = ""),
                                 paste0("[Implementation of a Breeding Program](", s_cn_gel_url, "03_impl_bp.pdf)", collapse = ""),
                                 paste0("[Model Selection](", s_cn_gel_url, "04_model_sel.pdf)", collapse = ""),
                                 paste0("[Variance Components Estimation](", s_cn_gel_url, "05_vce.pdf)", collapse = ""),
                                 paste0("[Prediction of Breeding Value](", s_cn_gel_url, "06_pb.pdf)", collapse = "")
                               ))
knitr::kable(tbl_gel_chpt)
```


## Applied Statistical Methods

```{r, echo=FALSE}
s_cn_asm_url <- 'https://charlotte-ngs.github.io/gelasmss2021/cn_asm/'
tbl_asm_chpt <- tibble::tibble(Week = c(1, 2, 3, 4, 5),
                               Date = c('2021-02-22',
                                        '2021-03-01',
                                        '2021-03-08',
                                        '2021-03-15',
                                        '2021-03-22'),
                               Topic = c(
                                 paste0("[Introduction](", s_cn_asm_url, "01_intro.pdf)", collapse = ""),
                                 paste0("[Fixed Linear Effects Model](", s_cn_asm_url, "02_flem.pdf)", collapse = ''),
                                 paste0("[GBLUP](", s_cn_asm_url, "03_gblup.pdf)", collapse = ''),
                                 paste0("[LASSO](", s_cn_asm_url, "04_lasso.pdf)", collapse = ''),
                                 paste0("[Bayes](", s_cn_asm_url, "05_bayes.pdf)", collapse = '')
                               ))
knitr::kable(tbl_asm_chpt)
```


### Appendix and Bibliography

```{r, echo=FALSE}
tbl_asm_app <- tibble::tibble(Week = c(1,1,6),
                              Date = c('2021-02-22', '2021-02-22', '2021-03-29'),
                              Topic = c(
                                paste0("[Linear Algebra](", s_cn_asm_url, "91_app_lin_alg.pdf)", collapse = ""),
                                paste0("[Quantitative Genetics](", s_cn_asm_url, "92_app_qg.pdf)", collapse = ""),
                                paste0("[Bibliography](", s_cn_asm_url, "99_bibliography.pdf", collapse = "")
                              ))
knitr::kable(tbl_asm_app)
```

